FROM        node:slim

EXPOSE      3000

RUN         apt-get update \
            && apt-get install -y libssl-dev procps \
            && apt-get clean

WORKDIR     /api

ENV         TZ=UTC

ENTRYPOINT ["/bin/sh", "-c" , "npm run migrate:deploy && npm run start:dev"]
