version: "3.9"
services:
    # Api
    api:
        container_name: api-fws
        build:
            context: ./
            dockerfile: Dockerfile.development
        ports:
            - 3000:3000
        volumes:
            - ./api:/api
        networks:
            - servers-network
        depends_on:
            - postgres
            - mongo

    # PostgreSQL
    postgres:
        container_name: postgres-fws
        image: postgres:13.1
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
        hostname: postgres
        environment:
            POSTGRES_PASSWORD: 'Postgres2023'
        ports:
            - 15432:5432
        volumes:
            - ./volumes/postgres-data:/var/lib/postgresql/data
        networks:
            - servers-network

    # Redis
    redis:
        container_name: redis-fws
        image: redis
        ports:
            - 6379:6379
        networks:
            - servers-network

networks:
    servers-network:
        driver: bridge

volumes:
    # Postgres volume
    postgres-data: